# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d855c25a88961d5356ad252d90fab8aebcb20f207a39fb5bc862001125a4b941fa375adbcb03d9a0c3649e673e52ee4d95ad1eafcce5e2dbeea7b24d5a5746b

test:
  secret_key_base: 3d7b773d533585e920a13b2cb046efb25daf0d3e8b0c0166a940b854beee7cb16fdebf70c9bfcf799d4a01108214be0ace3500d33f28d8c1f6358c6d51b857dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
